### ISSUE TITLE
Navigation event not kicking off dynamic property change pulling from query string parameters

### ISSUE THREAD

**Issue by rmaessen** [estruyf/spfx-navigation#1]
#### Description
I'm creating a webpart with a dynamic property that pulls its value from a query string parameter. I want to update the query string value from my app and use the new value without a page reload. I'm calling ```Navigation.navigate("<my-url?key=new-value>");``` on a button onclick with the expectation that it would inform the webpart of the URL change and set the dynamic property to new-value. I tried to get this to work in the workbench and deployed on my tenant, but while the change is reflected in the URL, the dynamic property does not get updated (and the webpart render function does not run). Do you have any suggestions on how to get it to work? Thank you!
 
#### Environment
- SharePoint Framework v1.7.0
- React

**Comment by nateforsyth** [comment]
Have you add the dynamic property to the web part componentDidUpdate method? Something like...

if (this.props.yourDynamicProperty !== prevProps.yourDynamicProperty) { this.render(); }

**Comment by estruyf** [comment]
@rmaessen where did you put the logic to check for your query string parameter? In some cases, it could be that the web part will not see the query string parameter. This could be related to the router logic and the web part thinking it doesn't have to be reloaded. In that case, what you could do is add an event handler for query string parameter changes, but normally it is not required.

**Comment by estruyf** [comment]
Closing the issue due no response.
