### ISSUE TITLE
Site url come with protocol

### ISSUE THREAD

**Issue by DRamalho92** [estruyf/spfx-navigation#4]
When you add a complete URL including protocol everything works as expect but if per example you as url parameter use "www.google.com", the code add that to the site relative Url generating something like:

> https://contoso.sharepoint.com/sites/www.google.com

Something like the below sample should correct the issue and keep you using the same protocol. 

```
if (Url.search(/^http[s]?\:\/\//) == -1) {
      Url = '//' + Url;
    }
```

Thanks for sharing  👍

**Comment by estruyf** [comment]
Would you like to do a PR?

**Comment by DRamalho92** [comment]
Sure. 😃
