### ISSUE TITLE
Partial Reload is not happening

### ISSUE THREAD

**Issue by Naveenrerd** [estruyf/spfx-navigation#6]
Hi,

Thanks for the great package. But the partial reload is not happening because of line 16 and 57. I guess the code on line 16 should be `const isLayoutPage = location.href.toLowerCase().indexOf("/_layouts/") > -1;`. Requesting you to check and update the code and help SPFx developers.

**Comment by estruyf** [comment]
Thanks for reporting this. The fix is now available in `v1.2.1`.
