### ISSUE TITLE
npm install cannot find module

### ISSUE THREAD

**Issue by Renevdo** [estruyf/spfx-navigation#7]
After importing as described, cannot resolve the module.
I also created a plan new project with Yeoman generator. I generated an SPFX Application Customizer, and added this module.

Error while importing on top of my .ts file: 
import { Navigation } from 'spfx-navigation';
[11:16:14] Error - [tsc] src/extensions/testabc/TestabcApplicationCustomizer.ts(10,28): error TS2307: Cannot find module 'spfx-navigation'.

![image](https://user-images.githubusercontent.com/7633914/86757567-85e5e780-c043-11ea-9b24-de67bbb8a713.png)

My package.json:

{
  "name": "test-navigation",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.10.0",
    "@microsoft/sp-application-base": "1.10.0",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-dialog": "1.10.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "spfx-navigation": "1.2.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by estruyf** [comment]
This has nothing to do with the package, but with a package that doesn't seem to be installed correctly. Can you check if the package is available in the node_modules folder?

**Comment by Renevdo** [comment]
The package is in the node_modules folder:

![image](https://user-images.githubusercontent.com/7633914/86799669-7df16c00-c072-11ea-8a38-688fca4f93f8.png)
![image](https://user-images.githubusercontent.com/7633914/86799868-b5601880-c072-11ea-956e-46b176cf11a1.png)

**Comment by estruyf** [comment]
Ok, I see the issue, for some reason the `lib` folder has been excluded from the package. I'll verify this.

**Comment by estruyf** [comment]
It seems a build action was missing from the Github workflow. `1.2.2` version is out and it should be fixed. Thanks for opening the issue.

**Comment by Renevdo** [comment]
You’re welcome. Thanks for your quick response!
